First task
mjawulski/learn-react-home-budget pull request #1
Opened 2022-03-17 15:41 UTC by marcinjasinski71

Hej :) 
Dokończyłem tabelę,  zgodnie z rozkładem mam przygotowanych pare pytań, które zapisałem:

1. W jaki sposób prawidłowo stylować komponenty w CSS? Czy mogę w tym przypadku pracować na App.css czy powinienem do komponentów mieć przygotowane osobne pliki CSS które zaimportuje w danym komponencie ? (pytanie chyba bardziej na przyszłość)

2. Idea z klockami jest bardzo logiczna. Czy to co robimy moglibyśmy zawrzeć w jednym komponencie (np. Transaction) w którym tworzylibyśmy kolejno funkcje, które są zawarte w osobnych komponentach?

3. Nie mam doświadczenia w pracy z kimś na GH, czy taka forma jak jest teraz jest ok? Stworzyłem branch testFeature, do niego zacommitowałem i wypchnąłem moje modyfikacje naszej apki. Następnie tak jak teraz - komunikacja po zakończonej pracy przez pull request i jeżeli uznasz, że to co wrzuciłem jest ok - wrzucamy na main?

4. Kurs z Reacta godny polecenia? :) Może coś na Udemy natrafiłeś? 

Pozdro,
Marcin:)

2022-03-20 12:10 UTC, mjawulski requested changes
Ogarnijmy jeszcze te style i bedzie mozna mergowac ;)

2022-03-20 12:10 UTC, mjawulski commented on public/index.html
> -    <title>React App</title>
Dobra zmiana ;)

2022-03-20 12:10 UTC, mjawulski commented on src/App.css
> +.titleName {
Dobrze jest jesli style sa definiowane mozliwie jak nablizej komponentu w ktorym sa uzywane. W tym przypadku powinnismy je zdefiniowac dla komponentu TransactionsSummary. W mailu objasnie co i jak :)

2022-03-20 12:10 UTC, mjawulski commented on src/App.css
> +	font-size: 1.6rem;
btw: skad wynika chec zmiany wielkosci fonta?

2022-03-20 12:10 UTC, mjawulski commented on src/TransactionsSummary/TransactionsTableRow/TransactionsTableRow.jsx
> +	// Tutaj zamiast null wpisz kod, ktory wyswietli wiersz tabeli z informacjami o dacie transakcji, sprzedawcy (merchant) i kwocie
Dobra praktyka jest niepozostawianie komentarzy w kodzie ktore nic nie wnosza ;)

2022-03-20 12:10 UTC, mjawulski commented on src/TransactionsSummary/TransactionsTableRow/TransactionsTableRow.jsx
> +			<td>{transaction.merchant}</td>
Świetnie! Dokladnie o to chodzilo!

2022-03-21 07:54 UTC, marcinjasinski71 commented on src/TransactionsSummary/TransactionsTableRow/TransactionsTableRow.jsx
> +	// Tutaj zamiast null wpisz kod, ktory wyswietli wiersz tabeli z informacjami o dacie transakcji, sprzedawcy (merchant) i kwocie
Naprawione:)

2022-03-21 07:59 UTC, marcinjasinski71 commented on public/index.html
> -    <title>React App</title>
ok:)

2022-03-21 11:22 UTC, marcinjasinski71 commented on src/App.css
> +	font-size: 1.6rem;
Prawdopodobnie sprawdzałem wieksza/mniejsza czcionke

2022-03-21 11:25 UTC, marcinjasinski71 commented
Dodałem komponent "AmountSummary" zliczający nasze Amount i zwracający rząd tabeli z podliczonymi wydatkami. 
Idąc Twoimi wskazówkami w mailu, aby ostylować (tudzież sprawdzić, czy po prostu to działa - stylowaniem będę się zajmować później) stworzyłem nowy moduł styles.module.css w którym zmieniłem tylko kolor tła i pogrubiłem czcionkę (aby Total wyróżniał się na tle innych pozycji w tabeli).

2022-03-29 20:27 UTC, mjawulski commented on src/TransactionsSummary/AmountSummary/AmountSummary.jsx
> +	const total = transactions.reduce(
Bardzo fajnie do tego podszedles. 
To co bym zasugerowal to ten kawalek kodu `transactions.reduce(...` wrzucilbym do funkcji w stylu `calculateTransactionTotalAmount` dzieki temu kod ktory piszesz bedzie czytelniejszy.

2022-03-29 20:27 UTC, mjawulski commented on src/TransactionsSummary/AmountSummary/AmountSummary.jsx
> +	const total = transactions.reduce(
Bedzie po prostu lepiej informowal jaka byla Twoja intencja

2022-03-29 20:29 UTC, mjawulski commented on src/TransactionsSummary/AmountSummary/AmountSummary.jsx
> +		<tr>
takie podejscie jest niebezpieczne. Tworzysz tutaj ukryta zaleznosc.
Zakladasz ze ten komponent bedzie wyswietlany w ramach tabeli.
(Uzycie <tr> poza tabela jest niewskazane).

Zamiast tego lepiej opakowac to w div/albo paragraf i w miejscu gdzie tego uzywasz przygotowac odpowiednia strukture. Mozemy sie zdzwonic to Ci pokaze na zywo o co chodzi

2022-03-29 20:30 UTC, merged